#include "mimetic/mimetic.hpp"
#include "test_utils.hpp"

#include <Eigen/Dense>
#include <moab/Core.hpp>

#include <cmath>
#include <exception>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>

namespace {

struct GaussPoint {
    double x;
    double w;
};

static const GaussPoint gauss10_table[10] = {
    {-0.9739065285171717, 0.0666713443086881},
    {-0.8650633666889845, 0.1494513491505806},
    {-0.6794095682990244, 0.2190863625159820},
    {-0.4333953941292472, 0.2692667193099963},
    {-0.1488743389816312, 0.2955242247147529},
    { 0.1488743389816312, 0.2955242247147529},
    { 0.4333953941292472, 0.2692667193099963},
    { 0.6794095682990244, 0.2190863625159820},
    { 0.8650633666889845, 0.1494513491505806},
    { 0.9739065285171717, 0.0666713443086881},
};

template <typename Func>
double integrate_edge_highorder(const Eigen::Vector2d& a, const Eigen::Vector2d& b, const Func& func)
{
    const double length = (b - a).norm();
    const Eigen::Vector2d mid = 0.5 * (a + b);
    const Eigen::Vector2d half_delta = 0.5 * (b - a);
    double sum = 0.0;
    for (const GaussPoint& q : gauss10_table) {
        sum += q.w * func(mid + q.x * half_delta);
    }
    return 0.5 * length * sum;
}

double legendre(const int degree, const double x)
{
    if (degree == 0) {
        return 1.0;
    }
    if (degree == 1) {
        return x;
    }

    double p_nm2 = 1.0;
    double p_nm1 = x;
    double p_n = x;
    for (int n = 2; n <= degree; ++n) {
        p_n = ((2.0 * n - 1.0) * x * p_nm1 - (n - 1.0) * p_nm2) / static_cast<double>(n);
        p_nm2 = p_nm1;
        p_nm1 = p_n;
    }
    return p_n;
}

using FieldFunc = Eigen::Vector2d(*)(const Eigen::Vector2d&);

// Exact field generated by the scalar potential
//   psi = x^3/3 + x y^2.
// Hence
//   u = grad psi = (x^2 + y^2, 2xy),
//   div u = 4x.
Eigen::Vector2d variable_divergence_exact_field(const Eigen::Vector2d& p)
{
    return Eigen::Vector2d(p.x() * p.x() + p.y() * p.y(),
                           2.0 * p.x() * p.y());
}

Eigen::Vector2d affine_exact_field(const Eigen::Vector2d& p)
{
    return Eigen::Vector2d(1.0 + 2.0 * p.x() - 1.0 * p.y(),
                           -0.5 + 0.75 * p.x() + 3.0 * p.y());
}

double halton(int index, int base)
{
    double result = 0.0;
    double f = 1.0 / base;
    int i = index;
    while (i > 0) {
        result += f * (i % base);
        i /= base;
        f /= base;
    }
    return result;
}

std::vector<Eigen::Vector2d> halton_seeds(const int count, const int offset)
{
    std::vector<Eigen::Vector2d> seeds;
    seeds.reserve(static_cast<std::size_t>(count));
    for (int i = 1; i <= count; ++i) {
        const int k = i + offset;
        seeds.emplace_back(0.05 + 0.90 * halton(k, 2),
                           0.05 + 0.90 * halton(k, 3));
    }
    return seeds;
}

std::vector<Eigen::Vector2d> clip_by_halfplane(const std::vector<Eigen::Vector2d>& polygon,
                                               const Eigen::Vector2d& normal,
                                               const double offset)
{
    std::vector<Eigen::Vector2d> output;
    if (polygon.empty()) {
        return output;
    }

    auto inside = [&](const Eigen::Vector2d& p) { return normal.dot(p) <= offset + 1.0e-13; };
    auto intersect = [&](const Eigen::Vector2d& a, const Eigen::Vector2d& b) {
        const double da = normal.dot(a) - offset;
        const double db = normal.dot(b) - offset;
        return a + (da / (da - db)) * (b - a);
    };

    Eigen::Vector2d previous = polygon.back();
    bool previous_inside = inside(previous);
    for (const Eigen::Vector2d& current : polygon) {
        const bool current_inside = inside(current);
        if (current_inside) {
            if (!previous_inside) {
                output.push_back(intersect(previous, current));
            }
            output.push_back(current);
        } else if (previous_inside) {
            output.push_back(intersect(previous, current));
        }
        previous = current;
        previous_inside = current_inside;
    }
    return output;
}

std::vector<Eigen::Vector2d> voronoi_cell_polygon(const Eigen::Vector2d& seed,
                                                  const std::vector<Eigen::Vector2d>& seeds)
{
    std::vector<Eigen::Vector2d> cell = {
        Eigen::Vector2d(0.0, 0.0),
        Eigen::Vector2d(1.0, 0.0),
        Eigen::Vector2d(1.0, 1.0),
        Eigen::Vector2d(0.0, 1.0),
    };
    for (const Eigen::Vector2d& other : seeds) {
        if ((other - seed).squaredNorm() < 1.0e-24) {
            continue;
        }
        const Eigen::Vector2d normal = 2.0 * (other - seed);
        const double offset = other.squaredNorm() - seed.squaredNorm();
        cell = clip_by_halfplane(cell, normal, offset);
        if (cell.size() < 3) {
            return {};
        }
    }
    return cell;
}

double polygon_area(const std::vector<Eigen::Vector2d>& polygon)
{
    return std::abs(mimetic::signed_area(polygon));
}

int resolved_cell_moment_order_for_test(const int num_edges, const int order)
{
    static_cast<void>(num_edges);
    return std::max(1, order - 1);
}

struct CellInfo {
    moab::EntityHandle handle;
    std::vector<Eigen::Vector2d> points;
};

std::vector<CellInfo> create_quad_mesh(moab::Core& mb, const int nx, const int ny)
{
    std::vector<CellInfo> cells;
    const double dx = 1.0 / nx;
    const double dy = 1.0 / ny;
    for (int j = 0; j < ny; ++j) {
        for (int i = 0; i < nx; ++i) {
            const double x0 = i * dx;
            const double y0 = j * dy;
            const std::vector<Eigen::Vector2d> pts = {
                Eigen::Vector2d(x0, y0),
                Eigen::Vector2d(x0 + dx, y0),
                Eigen::Vector2d(x0 + dx, y0 + dy),
                Eigen::Vector2d(x0, y0 + dy),
            };
            cells.push_back(CellInfo{mimetic::create_polygon(mb, pts), pts});
        }
    }
    std::vector<moab::EntityHandle> polygons;
    polygons.reserve(cells.size());
    for (const CellInfo& cell : cells) {
        polygons.push_back(cell.handle);
    }
    mimetic::merge_polygon_vertices(mb, polygons);
    return cells;
}

std::vector<CellInfo> create_voronoi_mesh(moab::Core& mb,
                                          const std::vector<Eigen::Vector2d>& seeds)
{
    std::vector<CellInfo> cells;
    for (const Eigen::Vector2d& seed : seeds) {
        const std::vector<Eigen::Vector2d> polygon = voronoi_cell_polygon(seed, seeds);
        if (polygon.size() < 3 || polygon_area(polygon) < 1.0e-12) {
            continue;
        }
        cells.push_back(CellInfo{mimetic::create_polygon(mb, polygon), polygon});
    }
    std::vector<moab::EntityHandle> polygons;
    polygons.reserve(cells.size());
    for (const CellInfo& cell : cells) {
        polygons.push_back(cell.handle);
    }
    mimetic::merge_polygon_vertices(mb, polygons);
    return cells;
}

std::vector<moab::EntityHandle> handles(const std::vector<CellInfo>& cells)
{
    std::vector<moab::EntityHandle> result;
    result.reserve(cells.size());
    for (const CellInfo& cell : cells) {
        result.push_back(cell.handle);
    }
    return result;
}

std::vector<double> exact_edge_moments_absolute(const Eigen::Vector2d& a,
                                                const Eigen::Vector2d& b,
                                                const int order,
                                                const FieldFunc& field)
{
    std::vector<double> moments(static_cast<std::size_t>(order + 1), 0.0);
    const Eigen::Vector2d delta = b - a;
    const double length = delta.norm();
    const double denom = delta.squaredNorm();
    const Eigen::Vector2d normal(delta.y(), -delta.x());
    for (int degree = 0; degree <= order; ++degree) {
        moments[degree] = integrate_edge_highorder(a, b, [&](const Eigen::Vector2d& p) {
            const double t = (denom > 0.0) ? (2.0 * (p - a).dot(delta) / denom - 1.0) : 0.0;
            return field(p).dot(normal / length) * legendre(degree, t);
        });
    }
    return moments;
}

std::vector<Eigen::Vector2d> exact_cell_vector_moments(const mimetic::LocalPolygon& poly,
                                                       const int order,
                                                       const FieldFunc& field)
{
    std::vector<Eigen::Vector2d> moments;
    const Eigen::Vector2d center = Eigen::Vector2d::Zero();
    for (int total_degree = 0; total_degree <= order; ++total_degree) {
        for (int a_pow = total_degree; a_pow >= 0; --a_pow) {
            const int b_pow = total_degree - a_pow;
            Eigen::Vector2d integral = Eigen::Vector2d::Zero();
            for (std::size_t i = 0; i < poly.points.size(); ++i) {
                const Eigen::Vector2d a = center;
                const Eigen::Vector2d b = poly.points[i];
                const Eigen::Vector2d c = poly.points[(i + 1) % poly.points.size()];
                integral.x() += mimetic::integrate_triangle_scalar(a, b, c, [&](const Eigen::Vector2d& p) {
                    return field(p + poly.centroid).x() *
                           std::pow(p.x(), a_pow) * std::pow(p.y(), b_pow);
                });
                integral.y() += mimetic::integrate_triangle_scalar(a, b, c, [&](const Eigen::Vector2d& p) {
                    return field(p + poly.centroid).y() *
                           std::pow(p.x(), a_pow) * std::pow(p.y(), b_pow);
                });
            }
            moments.push_back(integral);
        }
    }
    return moments;
}

void set_source_edge_moments_exact(moab::Core& mb,
                                   mimetic::PlanarMomentInterpolator& interpolator,
                                   const moab::EntityHandle polygon,
                                   const int order,
                                   const FieldFunc& field)
{
    const mimetic::LocalPolygon poly = mimetic::local_polygon(mb, polygon);
    const std::vector<mimetic::LocalEdge> edges = mimetic::local_edges(mb, poly);
    for (std::size_t edge_index = 0; edge_index < edges.size(); ++edge_index) {
        const Eigen::Vector2d a = poly.centroid + edges[edge_index].a;
        const Eigen::Vector2d b = poly.centroid + edges[edge_index].b;
        interpolator.set_source_edge_moments(polygon, edge_index, exact_edge_moments_absolute(a, b, order, field));
    }
}

struct ErrorSummary {
    double max_source_moment_residual = 0.0;
    double max_source_point_error = 0.0;
    double l2_target_moment0_error = 0.0;
    double l2_target_all_error = 0.0;
    double max_target_moment_error = 0.0;
    double max_conforming_target_moment_error = 0.0;
    double max_conforming_target_divergence_residual = 0.0;
    double relative_conforming_correction = 0.0;
};

ErrorSummary run_case(const std::string& label,
                      moab::Core& mb,
                      const std::vector<CellInfo>& source_cells,
                      const std::vector<CellInfo>& target_cells,
                      const FieldFunc& field,
                      const int order)
{
    std::cout << "\n=== " << label << " ===\n";

    mimetic::PlanarMomentInterpolator high_order(mb);
    mimetic::MomentMethodOptions options;
    options.edge_moment_order = order;
    options.cell_moment_order = std::max(1, order - 1);
    options.quadrature_points = 10;
    options.regularization = 1.0e-12;

    ErrorSummary summary;

    for (const CellInfo& source : source_cells) {
        const mimetic::LocalPolygon poly = mimetic::local_polygon(mb, source.handle);
        const int cell_order = resolved_cell_moment_order_for_test(
            static_cast<int>(mimetic::local_edges(mb, poly).size()), order);
        set_source_edge_moments_exact(mb, high_order, source.handle, options.edge_moment_order, field);
        high_order.set_source_cell_vector_moments(
            source.handle,
            exact_cell_vector_moments(poly, cell_order, field));

        const mimetic::MomentReconstruction reconstruction =
            high_order.reconstruct_source_polygon(source.handle, options);

        const std::vector<mimetic::LocalEdge> edges = mimetic::local_edges(mb, poly);
        summary.max_source_point_error = std::max(
            summary.max_source_point_error,
            (high_order.velocity(reconstruction, Eigen::Vector2d::Zero()) -
             field(poly.centroid)).norm());
        for (std::size_t edge_index = 0; edge_index < edges.size(); ++edge_index) {
            const std::vector<double> exact = exact_edge_moments_absolute(poly.centroid + edges[edge_index].a,
                                                                          poly.centroid + edges[edge_index].b,
                                                                          options.edge_moment_order,
                                                                          field);
            const std::vector<double> recovered =
                high_order.edge_moments(reconstruction, edges[edge_index].a, edges[edge_index].b, options.edge_moment_order);
            for (int degree = 0; degree <= options.edge_moment_order; ++degree) {
                summary.max_source_moment_residual =
                    std::max(summary.max_source_moment_residual, std::abs(recovered[degree] - exact[degree]));
            }
        }
    }

    const mimetic::EdgeMomentTransferResult high_transfer =
        high_order.transfer_source_to_target_edge_moments(handles(source_cells), handles(target_cells), options.edge_moment_order);
    const mimetic::ConformingEdgeMomentTransferResult conforming =
        high_order.project_target_edge_moments_to_hdiv_conforming(handles(source_cells), handles(target_cells), high_transfer);

    std::size_t dof = 0;
    double conforming_delta_num = 0.0;
    double conforming_delta_den = 0.0;
    for (const CellInfo& target : target_cells) {
        const mimetic::LocalPolygon poly = mimetic::local_polygon(mb, target.handle);
        const std::vector<mimetic::LocalEdge> edges = mimetic::local_edges(mb, poly);
        double exact_divergence_integral = 0.0;
        double conforming_divergence_integral = 0.0;
        for (const mimetic::LocalEdge& edge : edges) {
            const Eigen::Vector2d a = poly.centroid + edge.a;
            const Eigen::Vector2d b = poly.centroid + edge.b;
            const std::vector<double> exact = exact_edge_moments_absolute(a, b, options.edge_moment_order, field);

            const std::vector<double>& high_moments = high_transfer.target_moments[dof];
            const std::vector<double>& conforming_moments = conforming.target_moments[dof];

            const double high_m0_error = high_moments[0] - exact[0];
            summary.l2_target_moment0_error += high_m0_error * high_m0_error;
            summary.max_target_moment_error =
                std::max(summary.max_target_moment_error, std::abs(high_m0_error));
            exact_divergence_integral += exact[0];
            conforming_divergence_integral += conforming_moments[0];

            for (int degree = 0; degree <= options.edge_moment_order; ++degree) {
                const double error = high_moments[degree] - exact[degree];
                summary.l2_target_all_error += error * error;
                summary.max_target_moment_error =
                    std::max(summary.max_target_moment_error, std::abs(error));

                const double conf_error = conforming_moments[degree] - exact[degree];
                summary.max_conforming_target_moment_error =
                    std::max(summary.max_conforming_target_moment_error, std::abs(conf_error));

                const double delta = conforming_moments[degree] - high_moments[degree];
                conforming_delta_num += delta * delta;
                conforming_delta_den += exact[degree] * exact[degree];
            }
            ++dof;
        }
        summary.max_conforming_target_divergence_residual =
            std::max(summary.max_conforming_target_divergence_residual,
                     std::abs(conforming_divergence_integral - exact_divergence_integral));
    }

    summary.l2_target_moment0_error = std::sqrt(summary.l2_target_moment0_error);
    summary.l2_target_all_error = std::sqrt(summary.l2_target_all_error);
    summary.relative_conforming_correction =
        (conforming_delta_den > 1.0e-30) ? std::sqrt(conforming_delta_num / conforming_delta_den)
                                         : std::sqrt(conforming_delta_num);

    std::cout << std::scientific << std::setprecision(6)
              << "  max_source_moment_residual = " << summary.max_source_moment_residual << "\n"
              << "  max_source_point_error     = " << summary.max_source_point_error << "\n"
              << "  p" << order << " target moment-0 L2      = " << summary.l2_target_moment0_error << "\n"
              << "  p" << order << " target all-moment L2    = " << summary.l2_target_all_error << "\n"
              << "  p" << order << " max target moment error = " << summary.max_target_moment_error << "\n"
              << "  conforming max moment err  = " << summary.max_conforming_target_moment_error << "\n"
              << "  conforming max div resid   = " << summary.max_conforming_target_divergence_residual << "\n"
              << "  conforming rel correction  = " << summary.relative_conforming_correction << "\n";

    bool ok = true;
    ok = mimetic::test::near(summary.max_source_moment_residual, 0.0, 1.0e-10,
                             label + " source edge-moment reproduction") && ok;
    ok = mimetic::test::near(summary.max_source_point_error, 0.0, 1.0e-10,
                             label + " source pointwise reconstruction") && ok;
    ok = mimetic::test::near(summary.l2_target_moment0_error, 0.0, 1.0e-10,
                             label + " target flux transfer") && ok;
    ok = mimetic::test::near(summary.l2_target_all_error, 0.0, 2.0e-10,
                             label + " target moment transfer") && ok;
    ok = mimetic::test::near(summary.max_conforming_target_moment_error, 0.0, 2.0e-10,
                             label + " conforming target moment transfer") && ok;
    ok = mimetic::test::near(summary.max_conforming_target_divergence_residual, 0.0, 5.0e-13,
                             label + " conforming target divergence balance") && ok;
    ok = mimetic::test::near(summary.relative_conforming_correction, 0.0, 2.0e-10,
                             label + " conforming correction on exact field") && ok;

    if (!ok) {
        throw std::runtime_error("High-order edge-moment validation failed for " + label);
    }

    return summary;
}

}  // namespace

int main()
{
    try {
        std::cout << "--- High-Order Edge Moment Reconstruction Test ---\n";

        {
            moab::Core mb;
            const std::vector<CellInfo> source = create_quad_mesh(mb, 2, 3);
            const std::vector<CellInfo> target = create_quad_mesh(mb, 3, 4);
            run_case("quad to quad p1 affine", mb, source, target, affine_exact_field, 1);
        }

        {
            moab::Core mb;
            const std::vector<CellInfo> source = create_voronoi_mesh(mb, halton_seeds(7, 0));
            const std::vector<CellInfo> target = create_voronoi_mesh(mb, halton_seeds(10, 200));
            run_case("voronoi to voronoi p1 affine", mb, source, target, affine_exact_field, 1);
        }

        {
            moab::Core mb;
            const std::vector<CellInfo> source = create_quad_mesh(mb, 2, 3);
            const std::vector<CellInfo> target = create_quad_mesh(mb, 3, 4);
            run_case("quad to quad p2 variable", mb, source, target, variable_divergence_exact_field, 2);
        }

        {
            moab::Core mb;
            const std::vector<CellInfo> source = create_voronoi_mesh(mb, halton_seeds(7, 0));
            const std::vector<CellInfo> target = create_voronoi_mesh(mb, halton_seeds(10, 200));
            run_case("voronoi to voronoi p2 variable", mb, source, target, variable_divergence_exact_field, 2);
        }

        std::cout << "\n[SUCCESS] Unified higher-order edge moments recover exact p=1 and p=2 fields on quads and polygons.\n";
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "[ERROR] " << e.what() << "\n";
        return 1;
    }
}
